#-----------------------------------------------------------------------------#
#   .travis.yml                                                               #
#                                                                             #
#   Copyright Â© 2015-2017, Rajiv Bakulesh Shah, original author.              #
#   All rights reserved.                                                      #
#-----------------------------------------------------------------------------#



language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
services: redis-server
script:
  - coverage3 run -m unittest discover --start-directory tests --verbose
  - coverage3 report
  - pyflakes setup.py pottery/*\.py tests/*\.py
